CREATE TABLE IF NOT EXISTS todos (
  id         SERIAL PRIMARY KEY,
  title      VARCHAR(255) NOT NULL,
  completed  BOOLEAN NOT NULL DEFAULT FALSE,
  position   INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
